# Generated by Django 2.1.8 on 2019-05-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='Dong',
        ),
    ]
