# Generated by Django 2.1.8 on 2019-05-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190512_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dong',
            name='pub_date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
