# Generated by Django 2.1.8 on 2019-05-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190512_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dong',
            old_name='writter',
            new_name='name',
        ),
    ]
